[package]
name = "emojify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.3.2"
attohttpc = "0.28.0"
gif = "0.13.1"
image = "0.24.6"
itertools = "0.10.5"
maplit = "1.0.2"
